export const SCENES = [
  {
    id: 'warmup',
    icon: '🌙',
    accent: 'peach',
    levels: [1, 2],
    zh: { title: '升温小情调', subtitle: '轻松暧昧，先把气氛拉满', button: '开始热身' },
    en: { title: 'Slow Spark', subtitle: 'Soft flirting to warm up the room', button: 'Warm up' },
  },
  {
    id: 'truth',
    icon: '💬',
    accent: 'violet',
    types: ['truth'],
    levels: [1, 2, 3],
    zh: { title: '暖昧小问答', subtitle: '说一点真心话，靠近一点点', button: '抽问题' },
    en: { title: 'Tender Truths', subtitle: 'Honest questions that pull you closer', button: 'Draw truth' },
  },
  {
    id: 'listen',
    icon: '🎧',
    accent: 'sky',
    types: ['care', 'truth'],
    levels: [1, 2],
    zh: { title: '乖乖听你话', subtitle: '一方指挥，一方只负责配合与反馈', button: '进入角色' },
    en: { title: 'Lead & Follow', subtitle: 'One leads gently, one follows with feedback', button: 'Play roles' },
  },
  {
    id: 'tease',
    icon: '🫦',
    accent: 'rose',
    types: ['kiss', 'touch', 'dare'],
    levels: [2, 3, 4],
    zh: { title: '悄悄进后门', subtitle: '撩拨、暂停、再靠近，适合慢慢升级', button: '开始撩拨' },
    en: { title: 'Tease & Pause', subtitle: 'Build tension with tiny steps and stops', button: 'Start teasing' },
  },
  {
    id: 'dice',
    icon: '🎲',
    accent: 'gold',
    types: ['dice', 'dare'],
    levels: [1, 2, 3],
    zh: { title: '暖味骰子', subtitle: '部位、动作、时长随机组合', button: '掷骰子' },
    en: { title: 'Cozy Dice', subtitle: 'Random body-safe action, area and time', button: 'Roll dice' },
  },
  {
    id: 'wheel',
    icon: '🎡',
    accent: 'magenta',
    types: ['kiss', 'touch', 'dare', 'prop'],
    levels: [1, 2, 3, 4],
    zh: { title: '小爱转盘', subtitle: '一转定任务，还能导入自己的内容', button: '去转盘' },
    en: { title: 'Spark Wheel', subtitle: 'Spin for a prompt, then customize the deck', button: 'Spin wheel' },
  },
  {
    id: 'heat',
    icon: '🔥',
    accent: 'hot',
    types: ['dare', 'touch', 'prop', 'pose'],
    levels: [3, 4, 5],
    zh: { title: '激情一把梭', subtitle: '更大胆，但每一步都可以跳过', button: '进入高潮段' },
    en: { title: 'Daring Round', subtitle: 'Bolder prompts, every step skippable', button: 'Go bolder' },
  },
  {
    id: 'random',
    icon: '✨',
    accent: 'rainbow',
    levels: [1, 2, 3, 4, 5],
    zh: { title: '随机/渐进', subtitle: '从轻到重自动升温，最后回到温柔收尾', button: '随机探索' },
    en: { title: 'Progressive Mix', subtitle: 'A ramp from soft to bold, ending with care', button: 'Explore' },
  },
  {
    id: 'pose',
    icon: '🃏',
    accent: 'indigo',
    types: ['pose'],
    levels: [2, 3, 4, 5],
    zh: { title: '姿势卡', subtitle: '不画露骨图，用文字和边界提示来玩', button: '抽姿势' },
    en: { title: 'Pose Cards', subtitle: 'Text-first ideas with comfort notes', button: 'Draw pose' },
  },
  {
    id: 'aftercare',
    icon: '🫶',
    accent: 'mint',
    types: ['aftercare', 'care'],
    levels: [1, 2, 3],
    zh: { title: '抱抱收尾', subtitle: '把亲密体验落在安全感里', button: '温柔收尾' },
    en: { title: 'Aftercare', subtitle: 'Land the night with warmth and safety', button: 'Wind down' },
  },
];

export const TOOLS = [
  { id: 'boundary', icon: '🧭', zh: { title: '边界清单', subtitle: 'Yes / Maybe / No 双人匹配' }, en: { title: 'Boundary Match', subtitle: 'Yes / Maybe / No for both of you' } },
  { id: 'props', icon: '🧺', zh: { title: '道具选择', subtitle: '生成今晚准备清单' }, en: { title: 'Prop Picker', subtitle: 'Make a preparation list' } },
  { id: 'timer', icon: '⏱️', zh: { title: '爱计时', subtitle: '按摩、亲吻、暂停都能计时' }, en: { title: 'Intimacy Timer', subtitle: 'Time massages, kisses and pauses' } },
  { id: 'editor', icon: '🧪', zh: { title: '内容实验室', subtitle: '新增、导入、导出自定义题库' }, en: { title: 'Content Lab', subtitle: 'Add, import and export prompts' } },
  { id: 'settings', icon: '⚙️', zh: { title: '设置', subtitle: '语言、隐私、重置与备份' }, en: { title: 'Settings', subtitle: 'Language, privacy, reset and backup' } },
];

export const PROPS = [
  { id: 'water', level: 1, zh: '水和纸巾', en: 'Water and tissues' },
  { id: 'playlist', level: 1, zh: '播放列表', en: 'Playlist' },
  { id: 'lamp', level: 1, zh: '小夜灯/氛围灯', en: 'Lamp or mood light' },
  { id: 'blanket', level: 1, zh: '毯子', en: 'Blanket' },
  { id: 'fruit', level: 1, zh: '水果/小零食', en: 'Fruit or snacks' },
  { id: 'cards', level: 1, zh: '纸笔', en: 'Paper and pen' },
  { id: 'timer', level: 1, zh: '计时器', en: 'Timer' },
  { id: 'pillow', level: 1, zh: '靠枕', en: 'Pillows' },
  { id: 'mirror', level: 2, zh: '镜子', en: 'Mirror' },
  { id: 'blindfold', level: 2, zh: '眼罩', en: 'Blindfold' },
  { id: 'ice', level: 2, zh: '冰块', en: 'Ice cube' },
  { id: 'feather', level: 2, zh: '羽毛/丝巾', en: 'Feather or scarf' },
  { id: 'massage-oil', level: 2, zh: '按摩油/润肤乳', en: 'Massage oil or lotion' },
  { id: 'low-temp-candle', level: 3, zh: '低温蜡烛', en: 'Low-temp candle' },
  { id: 'private-camera', level: 3, zh: '只存在本地的相机', en: 'Local-only camera' },
  { id: 'toy', level: 3, zh: '双方认可的小玩具', en: 'Toy you both approve' },
  { id: 'lubricant', level: 3, zh: '润滑剂', en: 'Lubricant' },
  { id: 'condoms', level: 3, zh: '安全套/保护用品', en: 'Condoms or protection' },
  { id: 'towel', level: 1, zh: '毛巾', en: 'Towel' },
  { id: 'charger', level: 1, zh: '手机充电器', en: 'Phone charger' },
  { id: 'bath', level: 2, zh: '热水/沐浴用品', en: 'Warm shower supplies' },
  { id: 'cleaner', level: 2, zh: '清洁用品', en: 'Clean-up supplies' },
];

export const BOUNDARY_ITEMS = [
  { id: 'deep-kissing', level: 1, zh: '深吻', en: 'Deep kissing' },
  { id: 'neck-kiss', level: 1, zh: '脖颈亲吻', en: 'Neck kisses' },
  { id: 'massage', level: 1, zh: '全身按摩', en: 'Full body massage' },
  { id: 'compliments', level: 1, zh: '直白夸奖', en: 'Direct compliments' },
  { id: 'eye-contact', level: 1, zh: '长时间对视', en: 'Long eye contact' },
  { id: 'role-lead', level: 2, zh: '一方温柔指挥', en: 'One partner gently leads' },
  { id: 'blindfold', level: 2, zh: '眼罩', en: 'Blindfold' },
  { id: 'ice-play', level: 2, zh: '冰块触碰', en: 'Ice touch' },
  { id: 'mirror', level: 2, zh: '镜前互动', en: 'Mirror play' },
  { id: 'light-restraint', level: 3, zh: '轻度限制动作', en: 'Light restraint' },
  { id: 'sextalk', level: 3, zh: '露骨一点的情话', en: 'More explicit talk' },
  { id: 'photos', level: 3, zh: '私密照片（只本地保存）', en: 'Private photos kept local' },
  { id: 'toys', level: 3, zh: '小玩具', en: 'Toys' },
  { id: 'edging', level: 4, zh: '靠近高潮后暂停', en: 'Tease close, then pause' },
  { id: 'oral', level: 4, zh: '口欲互动', en: 'Oral intimacy' },
  { id: 'penetration', level: 4, zh: '进入式亲密', en: 'Penetrative intimacy' },
  { id: 'aftercare', level: 1, zh: '结束后的拥抱/复盘', en: 'Aftercare and check-in' },
  { id: 'no-phone', level: 1, zh: '全程不拍照', en: 'No photos at all' },
  { id: 'safe-word', level: 1, zh: '安全词/暂停手势', en: 'Safeword or pause signal' },
];

export const DICE = {
  actions: [
    { zh: '亲吻', en: 'kiss' }, { zh: '按摩', en: 'massage' }, { zh: '轻咬', en: 'nibble' }, { zh: '用气息靠近', en: 'breathe near' },
    { zh: '夸奖', en: 'praise' }, { zh: '慢慢触碰', en: 'touch slowly' }, { zh: '停住不动', en: 'freeze' }, { zh: '耳边说话', en: 'whisper' },
  ],
  areas: [
    { zh: '手心', en: 'palm' }, { zh: '手臂', en: 'arm' }, { zh: '肩颈', en: 'neck/shoulders' }, { zh: '耳边', en: 'ear' },
    { zh: '后背', en: 'back' }, { zh: '腰侧', en: 'waist' }, { zh: '大腿外侧', en: 'outer thigh' }, { zh: '双方同意的敏感处', en: 'a mutually approved sensitive spot' },
  ],
  times: [15, 30, 45, 60, 90, 120],
};

export const WHEEL_PRESETS = {
  zh: {
    soft: ['牵手对视', '亲吻额头', '耳边夸奖', '肩颈按摩', '交换一个秘密', '慢慢拥抱', '闭眼猜触碰', '30 秒不笑场'],
    spicy: ['轻咬一下', '只许对方指挥', '暂停 30 秒', '冰块轻触', '用唇画路线', '贴近耳边说愿望', '镜前夸 TA', '抽一张姿势卡'],
    aftercare: ['抱抱一分钟', '说一句谢谢', '喝水休息', '问 TA 感受', '温柔亲吻', '整理床铺', '约定下次想玩什么', '复盘一个喜欢的瞬间'],
  },
  en: {
    soft: ['hold hands', 'forehead kiss', 'whisper praise', 'neck massage', 'share a secret', 'slow hug', 'guess the touch', '30s no laughing'],
    spicy: ['gentle nibble', 'partner leads', 'pause 30s', 'ice touch', 'trace with lips', 'whisper a wish', 'mirror praise', 'draw a pose card'],
    aftercare: ['one-minute hug', 'say thank you', 'drink water', 'check feelings', 'soft kiss', 'tidy up', 'plan next time', 'name a favorite moment'],
  },
};

export const BUILT_IN_CARDS = [
  { id: 't001', type: 'truth', level: 1, tags: ['warmup'], zh: '说出今天最想被 TA 怎么夸的一句话。', en: 'Tell your partner one compliment you want to hear tonight.' },
  { id: 't002', type: 'truth', level: 1, tags: ['warmup'], zh: '你第一次觉得 TA 很迷人的瞬间是什么？', en: 'When did you first find your partner magnetic?' },
  { id: 't003', type: 'truth', level: 1, tags: ['warmup'], zh: '现在把 TA 身上最让你安心的一个细节说出来。', en: 'Name one detail about your partner that makes you feel safe.' },
  { id: 't004', type: 'truth', level: 1, tags: ['warmup'], zh: '如果今晚有一个关键词，会是什么？温柔、刺激、慢一点，还是别的？', en: 'Pick a keyword for tonight: tender, daring, slow, or something else?' },
  { id: 't005', type: 'truth', level: 1, tags: ['truth'], zh: '告诉 TA：你最喜欢 TA 怎么看你。', en: 'Tell your partner how you like them to look at you.' },
  { id: 't006', type: 'truth', level: 1, tags: ['truth'], zh: '说一个你最近想被照顾的小需求。', en: 'Share one small way you would like to be cared for lately.' },
  { id: 't007', type: 'truth', level: 2, tags: ['truth'], zh: '你最容易被哪种亲密前奏打动？声音、气味、动作、眼神？', en: 'What kind of lead-in affects you most: voice, scent, movement, or eye contact?' },
  { id: 't008', type: 'truth', level: 2, tags: ['truth'], zh: '说一个你愿意今晚尝试、但需要 TA 慢慢来的事。', en: 'Name one thing you might try tonight if your partner goes slowly.' },
  { id: 't009', type: 'truth', level: 2, tags: ['truth'], zh: '你希望 TA 在靠近你之前先问哪一句？', en: 'What question would you like your partner to ask before getting closer?' },
  { id: 't010', type: 'truth', level: 2, tags: ['truth'], zh: '描述一个你觉得“很会”的吻，不用演，只描述。', en: 'Describe a kiss that feels skillful to you. No demo needed.' },
  { id: 't011', type: 'truth', level: 2, tags: ['truth'], zh: '你最喜欢被慢慢靠近，还是被突然抱住？为什么？', en: 'Do you prefer slow approach or a surprise hug? Why?' },
  { id: 't012', type: 'truth', level: 3, tags: ['truth', 'tease'], zh: '说一个你听到会脸红的称呼，允许跳过。', en: 'Share a name or phrase that makes you blush. Skip is allowed.' },
  { id: 't013', type: 'truth', level: 3, tags: ['truth', 'tease'], zh: '告诉 TA：你想让 TA 在你耳边说什么。', en: 'Tell your partner what you would like whispered in your ear.' },
  { id: 't014', type: 'truth', level: 3, tags: ['truth', 'tease'], zh: '你最想让 TA 主动的一个动作是什么？', en: 'What is one move you wish your partner would initiate?' },
  { id: 't015', type: 'truth', level: 3, tags: ['truth'], zh: '说出一个你现在“可能愿意”的 Maybe，不要立刻执行，只记录。', en: 'Name one “maybe” for tonight. Do not do it yet; just note it.' },
  { id: 't016', type: 'truth', level: 3, tags: ['truth'], zh: '哪种节奏最适合你：慢火、调皮、强烈、还是由 TA 观察？', en: 'What rhythm suits you: slow burn, playful, intense, or let your partner read you?' },
  { id: 't017', type: 'truth', level: 4, tags: ['truth', 'heat'], zh: '在明确同意的前提下，你最想把哪一个边界从 Maybe 试到 Yes？', en: 'With clear consent, which boundary might move from Maybe to Yes?' },
  { id: 't018', type: 'truth', level: 4, tags: ['truth', 'heat'], zh: '说一句更直接的愿望，只说不做，听完由对方确认感受。', en: 'Say one more direct desire; only say it, then let your partner check in.' },
  { id: 't019', type: 'truth', level: 4, tags: ['truth', 'heat'], zh: '你喜欢在更亲密时被看着、被抱住，还是被慢慢引导？', en: 'During stronger intimacy, do you like being watched, held, or slowly guided?' },
  { id: 't020', type: 'truth', level: 5, tags: ['truth', 'heat'], zh: '说一个非常成人的幻想，用“我好奇……”开头，并允许对方只回应 Maybe。', en: 'Share a very adult curiosity beginning with “I am curious about…”. Maybe is a valid answer.' },

  { id: 'k001', type: 'kiss', level: 1, tags: ['warmup'], zh: '{giver}亲吻{receiver}的手背，然后说一句今天喜欢 TA 的地方。', en: '{giver} kisses {receiver}\'s hand and names one thing they like today.' },
  { id: 'k002', type: 'kiss', level: 1, tags: ['warmup'], zh: '额头吻 3 秒，然后换人。', en: 'Forehead kiss for 3 seconds, then switch.' },
  { id: 'k003', type: 'kiss', level: 1, tags: ['warmup'], zh: '脸颊从左到右亲 3 下，每一下都慢一点。', en: 'Three cheek kisses from left to right, each one slower.' },
  { id: 'k004', type: 'kiss', level: 2, tags: ['kiss', 'tease'], zh: '{giver}靠近但先不亲，停 5 秒，等{receiver}点头后再亲。', en: '{giver} moves close but waits 5 seconds, then kisses only after {receiver} nods.' },
  { id: 'k005', type: 'kiss', level: 2, tags: ['kiss', 'tease'], zh: '只用唇轻触，不深入，持续 20 秒。', en: 'Use only light lip contact, no deeper kiss, for 20 seconds.' },
  { id: 'k006', type: 'kiss', level: 2, tags: ['kiss'], zh: '亲吻肩颈附近 30 秒，避开对方标记为 No 的区域。', en: 'Kiss around the neck and shoulders for 30 seconds, avoiding all No areas.' },
  { id: 'k007', type: 'kiss', level: 3, tags: ['kiss', 'tease'], zh: '由{receiver}用手指指路，{giver}只亲被允许的位置。', en: '{receiver} points the route; {giver} kisses only approved spots.' },
  { id: 'k008', type: 'kiss', level: 3, tags: ['kiss', 'tease'], zh: '深吻 15 秒，然后立刻停下对视 10 秒。', en: 'Deep kiss for 15 seconds, then stop and hold eye contact for 10 seconds.' },
  { id: 'k009', type: 'kiss', level: 3, tags: ['kiss'], zh: '用“亲一下就退开”的方式重复 5 次，越到后面越慢。', en: 'Kiss and pull away 5 times, slower each time.' },
  { id: 'k010', type: 'kiss', level: 4, tags: ['kiss', 'heat'], zh: '挑一个双方 Yes 的敏感位置，用亲吻和暂停玩 60 秒。', en: 'Choose a mutually Yes sensitive area and alternate kisses with pauses for 60 seconds.' },
  { id: 'k011', type: 'kiss', level: 4, tags: ['kiss', 'heat'], zh: '{receiver}可以随时说“慢一点/停一下/继续”，{giver}按指令亲吻 90 秒。', en: '{receiver} can say “slower/stop/continue”; {giver} follows with kisses for 90 seconds.' },
  { id: 'k012', type: 'kiss', level: 5, tags: ['kiss', 'heat'], zh: '只在双方明确 Yes 的成人范围内，进行一轮更深入的吻与贴近，60 秒后必须复盘感受。', en: 'Within clearly mutual adult Yes areas only, share a deeper round of kissing and closeness, then check in after 60 seconds.' },

  { id: 'c001', type: 'care', level: 1, tags: ['care', 'listen'], zh: '{giver}给{receiver}倒水/盖毯子，然后问：“这样舒服吗？”', en: '{giver} brings water or a blanket to {receiver}, then asks, “Is this comfortable?”' },
  { id: 'c002', type: 'care', level: 1, tags: ['care'], zh: '关掉一个干扰源：通知、强光、杂物，给今晚留出空间。', en: 'Remove one distraction: notifications, bright light, or clutter.' },
  { id: 'c003', type: 'care', level: 1, tags: ['care'], zh: '一起确认：今晚的安全词/暂停手势是什么？', en: 'Agree on tonight\'s safeword or pause signal.' },
  { id: 'c004', type: 'care', level: 1, tags: ['care'], zh: '每人说一个“今天不想碰”的地方。', en: 'Each person names one area they do not want touched today.' },
  { id: 'c005', type: 'care', level: 2, tags: ['care', 'listen'], zh: '{receiver}闭眼 20 秒，{giver}只用声音引导呼吸，不触碰。', en: '{receiver} closes their eyes for 20 seconds while {giver} guides breathing with voice only.' },
  { id: 'c006', type: 'care', level: 2, tags: ['care'], zh: '做一次 1 到 5 的舒适度打分，低于 4 就降级玩法。', en: 'Rate comfort from 1 to 5; if below 4, make the next prompt softer.' },
  { id: 'c007', type: 'care', level: 2, tags: ['care'], zh: '给 TA 一个“暂停也会被喜欢”的拥抱。', en: 'Give a hug that says pausing is still loved.' },
  { id: 'c008', type: 'care', level: 3, tags: ['care', 'listen'], zh: '由{receiver}连续给 3 个指令：靠近、停下、换地方；{giver}只练习听话。', en: '{receiver} gives three commands: closer, stop, move; {giver} practices listening only.' },

  { id: 'd001', type: 'dare', level: 1, tags: ['warmup'], zh: '不许亲吻，只能用眼神和夸奖让对方笑出来。', en: 'No kissing; use eye contact and praise to make your partner smile.' },
  { id: 'd002', type: 'dare', level: 1, tags: ['warmup'], zh: '{giver}把手放在{receiver}掌心，30 秒内不许说话。', en: '{giver} places a hand in {receiver}\'s palm; no talking for 30 seconds.' },
  { id: 'd003', type: 'dare', level: 1, tags: ['dare'], zh: '两人轮流说“我喜欢你……”直到有人笑场。', en: 'Take turns saying “I like you…” until someone laughs.' },
  { id: 'd004', type: 'dare', level: 1, tags: ['dare'], zh: '给 TA 起一个今晚专属的暧昧昵称。', en: 'Create a flirty nickname for your partner for tonight.' },
  { id: 'd005', type: 'dare', level: 2, tags: ['dare', 'tease'], zh: '{giver}从 10 厘米外慢慢靠近{receiver}，由对方说停。', en: '{giver} slowly approaches from 10 cm away; {receiver} says when to stop.' },
  { id: 'd006', type: 'dare', level: 2, tags: ['dare'], zh: '换一种声音说一句：“现在轮到我照顾你。”', en: 'In a different voice, say: “Now it\'s my turn to take care of you.”' },
  { id: 'd007', type: 'dare', level: 2, tags: ['dare'], zh: '背对 TA，猜 TA 用哪根手指轻触了你的肩。', en: 'Turn around and guess which finger touched your shoulder.' },
  { id: 'd008', type: 'dare', level: 2, tags: ['dice'], zh: '掷一次骰子：动作 + 区域 + 时间，双方都点头才执行。', en: 'Roll dice: action + area + time. Do it only if both nod.' },
  { id: 'd009', type: 'dare', level: 3, tags: ['dare', 'tease'], zh: '{receiver}把{giver}的手放到一个 Yes 区域，然后说“这里可以”。', en: '{receiver} places {giver}\'s hand on a Yes area and says, “Here is okay.”' },
  { id: 'd010', type: 'dare', level: 3, tags: ['dare', 'tease'], zh: '用一句话指挥 TA：慢一点、近一点、停一下，三选一。', en: 'Direct your partner with one phrase: slower, closer, or pause.' },
  { id: 'd011', type: 'dare', level: 3, tags: ['dare'], zh: '由{giver}在{receiver}耳边说一个不超过 8 个字的愿望。', en: '{giver} whispers a desire in no more than eight words.' },
  { id: 'd012', type: 'dare', level: 3, tags: ['dare'], zh: '把今晚的节奏调到 80% 慢，任何动作都拉长一倍。', en: 'Make tonight 80% slower; stretch every movement to double length.' },
  { id: 'd013', type: 'dare', level: 4, tags: ['dare', 'heat'], zh: '选择一个 Maybe，道具或玩法只试 30 秒；到点必须询问是否继续。', en: 'Choose one Maybe prop or play style for 30 seconds; ask before continuing.' },
  { id: 'd014', type: 'dare', level: 4, tags: ['dare', 'heat'], zh: '由{receiver}完全掌控 2 分钟：可以命令靠近、暂停、换方式。', en: '{receiver} controls 2 minutes: they may ask for closer, pause, or change.' },
  { id: 'd015', type: 'dare', level: 4, tags: ['dare', 'heat'], zh: '用“只差一点点”的节奏玩 60 秒，然后停下来抱住。', en: 'Play with an “almost there” rhythm for 60 seconds, then stop and hug.' },
  { id: 'd016', type: 'dare', level: 4, tags: ['dare', 'heat'], zh: '把灯光调暗，{giver}用低声说出下一步，{receiver}只回答 Yes / Maybe / No。', en: 'Dim the lights; {giver} softly proposes the next step, {receiver} answers Yes / Maybe / No.' },
  { id: 'd017', type: 'dare', level: 5, tags: ['dare', 'heat'], zh: '进入成人模式前暂停：双方各说一个 Yes、一个 No、一个安全词，然后只做共同 Yes。', en: 'Before adult mode: each person states one Yes, one No, and a safeword; do only shared Yes items.' },
  { id: 'd018', type: 'dare', level: 5, tags: ['dare', 'heat'], zh: '选择双方已经明确同意的一项更亲密玩法，设 3 分钟计时，中途任何一方可降级。', en: 'Choose one explicitly agreed intimate activity, set a 3-minute timer, and either person may downgrade anytime.' },

  { id: 'u001', type: 'touch', level: 1, tags: ['touch', 'warmup'], zh: '手指沿着 TA 的手腕到手肘慢慢走一遍。', en: 'Trace from your partner\'s wrist to elbow slowly.' },
  { id: 'u002', type: 'touch', level: 1, tags: ['touch'], zh: '肩颈按摩 60 秒，力度由被按摩的人打分。', en: 'Neck and shoulder massage for 60 seconds; receiver rates the pressure.' },
  { id: 'u003', type: 'touch', level: 1, tags: ['touch'], zh: '把 TA 的头发或衣领整理好，动作越慢越好。', en: 'Adjust your partner\'s hair or collar as slowly as possible.' },
  { id: 'u004', type: 'touch', level: 1, tags: ['touch'], zh: '只牵手不说话，30 秒后说一个感受词。', en: 'Hold hands silently; after 30 seconds, say one feeling word.' },
  { id: 'u005', type: 'touch', level: 2, tags: ['touch', 'tease'], zh: '{giver}用指尖轻触{receiver}后背，画一个只有你们懂的符号。', en: '{giver} draws a private symbol on {receiver}\'s back with fingertips.' },
  { id: 'u006', type: 'touch', level: 2, tags: ['touch'], zh: '闭眼猜触碰：TA 触碰一个安全区域，你猜位置。', en: 'Eyes-closed guess: your partner touches a safe area and you guess where.' },
  { id: 'u007', type: 'touch', level: 2, tags: ['touch'], zh: '用手掌贴住 TA 的后背，跟着 TA 呼吸 6 次。', en: 'Place your palm on your partner\'s back and follow six breaths.' },
  { id: 'u008', type: 'touch', level: 2, tags: ['touch'], zh: '隔着衣服，从肩膀到腰侧慢慢移动，任何不舒服马上停。', en: 'Over clothing, move from shoulder to waist slowly; stop at any discomfort.' },
  { id: 'u009', type: 'touch', level: 3, tags: ['touch', 'tease'], zh: '用羽毛/丝巾轻扫一个 Yes 区域 45 秒。', en: 'Use a feather or scarf over a Yes area for 45 seconds.' },
  { id: 'u010', type: 'touch', level: 3, tags: ['touch', 'tease'], zh: '冰块用纸巾包一下，只在双方同意的区域停留 3 秒。', en: 'Wrap an ice cube in tissue and touch only agreed areas for 3 seconds each.' },
  { id: 'u011', type: 'touch', level: 3, tags: ['touch'], zh: '{receiver}闭眼，{giver}在 3 个安全位置轻触；{receiver}选最喜欢的一个。', en: '{receiver} closes eyes; {giver} touches 3 safe spots; {receiver} picks the favorite.' },
  { id: 'u012', type: 'touch', level: 3, tags: ['touch'], zh: '用按摩油/润肤乳给手臂或肩颈做 2 分钟慢按摩。', en: 'Use lotion or massage oil on arms or shoulders for a 2-minute slow massage.' },
  { id: 'u013', type: 'touch', level: 4, tags: ['touch', 'heat'], zh: '选一个双方 Yes 的敏感区域，只用手背轻碰 60 秒。', en: 'Pick one mutually Yes sensitive area and touch only with the back of your hand for 60 seconds.' },
  { id: 'u014', type: 'touch', level: 4, tags: ['touch', 'heat'], zh: '{receiver}用 1-5 控制强度，{giver}每 15 秒询问一次。', en: '{receiver} controls intensity from 1-5; {giver} checks every 15 seconds.' },
  { id: 'u015', type: 'touch', level: 4, tags: ['touch', 'heat'], zh: '触碰 20 秒、暂停 10 秒，重复 3 轮；暂停时只能对视。', en: 'Touch 20 seconds, pause 10 seconds, repeat 3 times; during pause, only eye contact.' },
  { id: 'u016', type: 'touch', level: 5, tags: ['touch', 'heat'], zh: '只做双方共同 Yes 的成人触碰，设定 2 分钟，结束后必须喝水并确认感受。', en: 'Do only mutually Yes adult touch for 2 minutes, then drink water and check feelings.' },

  { id: 'p001', type: 'prop', level: 1, props: ['playlist', 'lamp'], tags: ['prop'], zh: '把歌单调成“慢”，灯光调暗，然后重新抽一张。', en: 'Set the playlist to slow, dim the lights, then draw another card.' },
  { id: 'p002', type: 'prop', level: 1, props: ['cards'], tags: ['prop'], zh: '各写一个今晚想要的词，交换后只读不解释。', en: 'Each writes one word they want tonight; swap and read only.' },
  { id: 'p003', type: 'prop', level: 1, props: ['blanket'], tags: ['prop'], zh: '用毯子把两个人裹在一起，拥抱 45 秒。', en: 'Wrap both of you in a blanket and hug for 45 seconds.' },
  { id: 'p004', type: 'prop', level: 2, props: ['mirror'], tags: ['prop', 'tease'], zh: '站到镜子前，每人说出对方今天最好看的一个地方。', en: 'Stand before a mirror and each name one beautiful thing about the other.' },
  { id: 'p005', type: 'prop', level: 2, props: ['blindfold'], tags: ['prop'], zh: '眼罩挑战：被戴眼罩的人只用 Yes / No / 慢一点 回答。', en: 'Blindfold challenge: the blindfolded partner answers only Yes / No / slower.' },
  { id: 'p006', type: 'prop', level: 2, props: ['fruit'], tags: ['prop'], zh: '用水果喂 TA 一口，必须先问“这样可以吗？”', en: 'Feed your partner one bite of fruit; ask “Is this okay?” first.' },
  { id: 'p007', type: 'prop', level: 2, props: ['ice'], tags: ['prop'], zh: '冰块只在手臂或肩颈移动 15 秒，然后立刻用手心暖回来。', en: 'Move ice over arm or shoulder for 15 seconds, then warm the spot with your palm.' },
  { id: 'p008', type: 'prop', level: 3, props: ['massage-oil'], tags: ['prop'], zh: '按摩油任务：选择一个非敏感区域，慢按摩 2 分钟。', en: 'Massage oil task: choose a non-sensitive area and massage slowly for 2 minutes.' },
  { id: 'p009', type: 'prop', level: 3, props: ['private-camera'], tags: ['prop'], zh: '相机只当道具：摆一个不露脸的亲密剪影，拍不拍由双方再次确认。', en: 'Use the camera as a prop: pose a no-face silhouette; confirm again before taking any photo.' },
  { id: 'p010', type: 'prop', level: 3, props: ['toy'], tags: ['prop', 'heat'], zh: '拿出一个双方都熟悉的小玩具，先只介绍它，不立即使用。', en: 'Bring out a toy you both know; introduce it without using it yet.' },
  { id: 'p011', type: 'prop', level: 4, props: ['blindfold', 'feather'], tags: ['prop', 'heat'], zh: '眼罩 + 羽毛：只在双方 Yes 区域玩 60 秒，必须有安全词。', en: 'Blindfold + feather: only on mutual Yes areas for 60 seconds; safeword required.' },
  { id: 'p012', type: 'prop', level: 4, props: ['low-temp-candle'], tags: ['prop', 'heat'], zh: '低温蜡烛只做演示：滴在自己手背测试，双方都确认再继续。', en: 'Low-temp candle demo only: test on your own hand first, continue only if both confirm.' },

  { id: 's001', type: 'pose', level: 2, tags: ['pose'], zh: '面对面坐着，膝盖相碰，30 秒内只能用眼神沟通。', en: 'Sit face-to-face with knees touching; communicate only with eyes for 30 seconds.' },
  { id: 's002', type: 'pose', level: 2, tags: ['pose'], zh: '一人坐着，一人站在身前，站着的人只负责被夸。', en: 'One sits, one stands in front; the standing partner only receives compliments.' },
  { id: 's003', type: 'pose', level: 2, tags: ['pose'], zh: '背后拥抱：抱住 45 秒，呼吸同步。', en: 'Back hug for 45 seconds and sync your breathing.' },
  { id: 's004', type: 'pose', level: 2, tags: ['pose'], zh: '躺在对方大腿上，听 TA 说 3 句喜欢。', en: 'Rest your head on your partner\'s lap and hear three things they like.' },
  { id: 's005', type: 'pose', level: 3, tags: ['pose', 'tease'], zh: '一人靠墙，一人靠近但不贴上，保持 10 秒后由靠墙的人决定下一步。', en: 'One leans on a wall; the other moves close without touching for 10 seconds; wall partner chooses next.' },
  { id: 's006', type: 'pose', level: 3, tags: ['pose'], zh: '沙发边缘坐姿：面对面，手只放在对方允许的位置。', en: 'Sofa edge pose: face each other, hands only on approved spots.' },
  { id: 's007', type: 'pose', level: 3, tags: ['pose'], zh: '拥抱转身：从背后抱住，慢慢转到面对面。', en: 'Hug from behind, then slowly turn to face each other.' },
  { id: 's008', type: 'pose', level: 3, tags: ['pose'], zh: '镜前并肩站，轮流说“我喜欢你这里”。', en: 'Stand side by side in a mirror and take turns saying “I like this about you.”' },
  { id: 's009', type: 'pose', level: 4, tags: ['pose', 'heat'], zh: '一人坐在床边，另一人跨坐但保持衣物与边界，先对视 20 秒。', en: 'One sits on the bed edge; the other straddles while respecting clothing and boundaries; start with 20 seconds of eye contact.' },
  { id: 's010', type: 'pose', level: 4, tags: ['pose', 'heat'], zh: '躺姿贴近：选择一个舒适姿势，只做拥抱、亲吻或双方 Yes 的动作。', en: 'Close lying pose: choose a comfortable position and do only hugging, kissing, or mutual Yes actions.' },
  { id: 's011', type: 'pose', level: 4, tags: ['pose', 'heat'], zh: '一人主导节奏，一人只用手势表达继续/慢点/停。', en: 'One controls rhythm; the other uses hand signals for continue/slower/stop.' },
  { id: 's012', type: 'pose', level: 5, tags: ['pose', 'heat'], zh: '成人姿势卡：只选择你们已共同同意的亲密姿势，先试 60 秒，不舒服立刻换。', en: 'Adult pose card: choose only a mutually agreed intimate position, try for 60 seconds, switch immediately if uncomfortable.' },

  { id: 'a001', type: 'aftercare', level: 1, tags: ['aftercare'], zh: '抱住 TA 60 秒，不评价表现，只说“谢谢你愿意和我玩”。', en: 'Hold your partner for 60 seconds; no performance talk, just say “Thank you for playing with me.”' },
  { id: 'a002', type: 'aftercare', level: 1, tags: ['aftercare'], zh: '每人说一个最喜欢的瞬间和一个下次想调整的地方。', en: 'Each person names one favorite moment and one thing to adjust next time.' },
  { id: 'a003', type: 'aftercare', level: 1, tags: ['aftercare'], zh: '喝水、盖毯子、亲吻额头，今晚先暂停。', en: 'Drink water, get a blanket, forehead kiss, and pause for tonight.' },
  { id: 'a004', type: 'aftercare', level: 1, tags: ['aftercare'], zh: '问 TA：“现在身体和心情各是几分？”', en: 'Ask: “What score are your body and mood right now?”' },
  { id: 'a005', type: 'aftercare', level: 2, tags: ['aftercare'], zh: '把刚才的 Maybe 标记一下：保留、降级、还是删除。', en: 'Mark the Maybe from earlier: keep, soften, or remove.' },
  { id: 'a006', type: 'aftercare', level: 2, tags: ['aftercare'], zh: '一起选一个“明天也能感受到被爱”的小行动。', en: 'Choose one small action that will make tomorrow feel loved too.' },
  { id: 'a007', type: 'aftercare', level: 2, tags: ['aftercare'], zh: '如果有拍照，立刻一起确认保存、删除或加密备份。', en: 'If any photo was taken, decide together now: keep, delete, or encrypted backup.' },
  { id: 'a008', type: 'aftercare', level: 3, tags: ['aftercare'], zh: '用 3 句话复盘：我喜欢、我需要、我下次想。', en: 'Debrief with three sentences: I liked, I need, next time I want.' },
  { id: 'a009', type: 'aftercare', level: 3, tags: ['aftercare'], zh: '给今晚起一个标题，保存到本地历史，不上传。', en: 'Give tonight a title and save it locally; no upload.' },
];
